version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      # - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build . -t node_app
      - run:
          name: Run tests
          command: |
            docker run --name temp -d -p 8888:8080 node_app 
            sleep 10
            curl "http://localhost:8888" 
  publish:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - run:
          name: Push application Docker image
          command: |
            docker login -u $DOCKERHUB_ID -p $DOCKERHUB_PASSWORD
            docker tag node_app excoffit/node_app
            docker push excoffit/node_app
workflows:
  my-workflow:
    jobs:
      - build
      - publish: 
          requires:
            - build
